# Generated by Django 3.1.3 on 2021-01-12 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20210107_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCivilModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='GeneroModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='pacientemodel',
            name='lugarNacimiento',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='pacientemodel',
            name='nacionalidad',
            field=models.CharField(default='argentino', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientemodel',
            name='numeroAfiliado',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='pacientemodel',
            name='telAlternativo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pacientemodel',
            name='coberturaMedica',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to='crm.coberturamedicamodel'),
        ),
        migrations.AlterField(
            model_name='pacientemodel',
            name='telMovil',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='DomicilioAlternativoPacienteModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=300)),
                ('numero', models.CharField(max_length=300)),
                ('piso', models.CharField(blank=True, max_length=300, null=True)),
                ('localidad', models.CharField(max_length=300)),
                ('codigoPostal', models.CharField(max_length=300)),
                ('paciente', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='crm.pacientemodel')),
                ('provincia', models.ForeignKey(
                    on_delete=django.db.models.deletion.RESTRICT, to='crm.provinciamodel')),
            ],
        ),
        migrations.AddField(
            model_name='pacientemodel',
            name='estadoCivil',
            field=models.ForeignKey(
                default='soltero', on_delete=django.db.models.deletion.RESTRICT, to='crm.estadocivilmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientemodel',
            name='genero',
            field=models.ForeignKey(
                default='otros', on_delete=django.db.models.deletion.RESTRICT, to='crm.generomodel'),
            preserve_default=False,
        ),
    ]
