# Generated by Django 3.1.3 on 2021-01-12 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0002_auto_20210112_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientemodel',
            name='areaALaQueSeDerivo',
        ),
        migrations.CreateModel(
            name='CuotasPagasModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correspondienteAlAno', models.CharField(max_length=300)),
                ('montoPagado', models.CharField(max_length=300)),
                ('fechaPago', models.DateField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.pacientemodel')),
                ('usuarioQueCargoPago', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
