# Generated by Django 3.1.4 on 2020-12-11 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20201209_1616'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Area',
            new_name='AreaModel',
        ),
        migrations.RenameModel(
            old_name='CoberturaMedica',
            new_name='CoberturaMedicaModel',
        ),
        migrations.RenameModel(
            old_name='Derivacion',
            new_name='DerivacionModel',
        ),
        migrations.RenameModel(
            old_name='Diagnostico',
            new_name='DiagnosticoModel',
        ),
        migrations.RenameModel(
            old_name='Domicilio',
            new_name='DomicilioModel',
        ),
        migrations.RenameModel(
            old_name='FormaClinica',
            new_name='FormaClinicaModel',
        ),
        migrations.RenameModel(
            old_name='Paciente',
            new_name='PacienteModel',
        ),
        migrations.RenameModel(
            old_name='Provincia',
            new_name='ProvinciaModel',
        ),
        migrations.RenameModel(
            old_name='Reunion',
            new_name='ReunionModel',
        ),
        migrations.RenameModel(
            old_name='Sintomas',
            new_name='SintomasModel',
        ),
        migrations.RenameModel(
            old_name='SituacionHabitacional',
            new_name='SituacionHabitacionalModel',
        ),
        migrations.RenameModel(
            old_name='SituacionLaboral',
            new_name='SituacionLaboralModel',
        ),
        migrations.RenameModel(
            old_name='Taller',
            new_name='TallerModel',
        ),
        migrations.RenameModel(
            old_name='TallerPaciente',
            new_name='TallerPacienteModel',
        ),
        migrations.RenameModel(
            old_name='TerapiasRehabilitacion',
            new_name='TerapiasRehabilitacionModel',
        ),
        migrations.RenameModel(
            old_name='Tratamiento',
            new_name='TratamientoModel',
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='UsuarioModel',
        ),
    ]
