# Generated by Django 3.1.3 on 2020-12-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20201212_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallermodel',
            name='pacientes',
            field=models.ManyToManyField(to='crm.PacienteModel'),
        ),
        migrations.DeleteModel(
            name='TallerPacienteModel',
        ),
    ]
