# Generated by Django 3.1.4 on 2020-12-15 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20201214_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunionmodel',
            name='areaAlQueSeDerivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crm.areamodel'),
        ),
        migrations.DeleteModel(
            name='DerivacionModel',
        ),
    ]
