# Generated by Django 3.1.4 on 2020-12-16 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0012_composicionfamiliarmodel_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=300)),
                ('fechaNacimiento', models.DateField()),
                ('telFijo', models.CharField(blank=True, max_length=300, null=True)),
                ('telMovil', models.CharField(max_length=300)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='crm.areamodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='pacientemodel',
            name='usuarioQueRealizoAlta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reunionmodel',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UsuarioModel',
        ),
    ]
