# Generated by Django 3.1.4 on 2021-01-06 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_auto_20210106_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunionmodel',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.pacientemodel'),
        ),
    ]
