# Generated by Django 3.1.4 on 2021-01-07 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_tallermodel_pacientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TallerPacienteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.pacientemodel')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.tallermodel')),
            ],
        ),
        migrations.AddField(
            model_name='pacientemodel',
            name='talleres',
            field=models.ManyToManyField(through='crm.TallerPacienteModel', to='crm.TallerModel'),
        ),
        migrations.AlterField(
            model_name='tallermodel',
            name='pacientes',
            field=models.ManyToManyField(through='crm.TallerPacienteModel', to='crm.PacienteModel'),
        ),
    ]
