# Generated by Django 3.1.4 on 2020-12-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=300)),
                ('nombre', models.CharField(max_length=300)),
                ('apellido', models.CharField(max_length=300)),
                ('fechaNacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telFijo', models.CharField(max_length=300)),
                ('telMovil', models.CharField(max_length=300)),
                ('fechaAlta', models.DateField(auto_now=True)),
                ('usuarioQueRealizoAlta_id', models.IntegerField()),
                ('areaALaQueSeDerivo_id', models.IntegerField()),
                ('esSocio', models.BooleanField(default=False)),
                ('fechaAsociacion', models.DateField()),
                ('fechaUltimaCuotaPaga', models.DateField()),
                ('recibeMailing', models.BooleanField(default=False)),
                ('coberturaMedica_id', models.IntegerField()),
                ('lugarDeAtencion', models.CharField(max_length=300)),
                ('neurologoCabecera', models.CharField(max_length=300)),
            ],
        ),
    ]
