# Generated by Django 3.1.3 on 2021-01-12 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CoberturaMedicaModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ComposicionFamiliarModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('vinculo', models.CharField(max_length=300)),
                ('nombre', models.CharField(max_length=300)),
                ('apellido', models.CharField(max_length=300)),
                ('fechaNacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telFijo', models.CharField(blank=True, max_length=300, null=True)),
                ('telMovil', models.CharField(max_length=300)),
                ('ocupacion', models.CharField(max_length=300)),
                ('esConviviente', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CuotaPagaModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('correspondienteAlAno', models.CharField(max_length=300)),
                ('montoPagado', models.CharField(max_length=300)),
                ('fechaPago', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticoModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DomicilioAlternativoPacienteModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=300)),
                ('numero', models.CharField(max_length=300)),
                ('piso', models.CharField(blank=True, max_length=300, null=True)),
                ('localidad', models.CharField(max_length=300)),
                ('codigoPostal', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DomicilioPacienteModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=300)),
                ('numero', models.CharField(max_length=300)),
                ('piso', models.CharField(blank=True, max_length=300, null=True)),
                ('localidad', models.CharField(max_length=300)),
                ('codigoPostal', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DomicilioUserExtendidoModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=300)),
                ('numero', models.CharField(max_length=300)),
                ('piso', models.CharField(blank=True, max_length=300, null=True)),
                ('localidad', models.CharField(max_length=300)),
                ('codigoPostal', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivilModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='FormaClinicaModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='GeneroModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoDeApoyoModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoDeApoyoPacienteModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('grupoDeApoyo', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='crm.grupodeapoyomodel')),
            ],
        ),
        migrations.CreateModel(
            name='PacienteModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=300, unique=True)),
                ('nombre', models.CharField(max_length=300)),
                ('apellido', models.CharField(max_length=300)),
                ('fechaNacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=300)),
                ('lugarNacimiento', models.CharField(max_length=300, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telFijo', models.CharField(blank=True, max_length=300, null=True)),
                ('telMovil', models.CharField(max_length=300, null=True)),
                ('telAlternativo', models.CharField(
                    blank=True, max_length=300, null=True)),
                ('fechaAlta', models.DateField(auto_now=True)),
                ('esSocio', models.BooleanField(default=False)),
                ('fechaAsociacion', models.DateField(blank=True, null=True)),
                ('fechaUltimaCuotaPaga', models.DateField(blank=True, null=True)),
                ('recibeMailing', models.BooleanField(default=False)),
                ('numeroAfiliado', models.CharField(max_length=300, null=True)),
                ('lugarDeAtencion', models.CharField(max_length=300)),
                ('neurologoCabecera', models.CharField(max_length=300)),
                ('fechaDiagnostico', models.DateField()),
                ('actividadFisica', models.BooleanField(default=False)),
                ('fumadorTabaco', models.BooleanField(default=False)),
                ('antecedentesEnfermedades', models.CharField(
                    blank=True, max_length=300, null=True)),
                ('tieneCUD', models.BooleanField(default=False)),
                ('fechaVencimientoCUD', models.DateField(blank=True, null=True)),
                ('coberturaMedica', models.ForeignKey(
                    on_delete=django.db.models.deletion.RESTRICT, to='crm.coberturamedicamodel')),
                ('estadoCivil', models.ForeignKey(
                    on_delete=django.db.models.deletion.RESTRICT, to='crm.estadocivilmodel')),
                ('genero', models.ForeignKey(
                    on_delete=django.db.models.deletion.RESTRICT, to='crm.generomodel')),
                ('gruposDeApoyo', models.ManyToManyField(
                    through='crm.GrupoDeApoyoPacienteModel', to='crm.GrupoDeApoyoModel')),
            ],
        ),
        migrations.CreateModel(
            name='ProvinciaModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ReunionModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('contenido', models.TextField()),
                ('areaAlQueSeDerivo', models.ForeignKey(blank=True, null=True,
                                                        on_delete=django.db.models.deletion.RESTRICT, to='crm.areamodel')),
                ('paciente', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='crm.pacientemodel')),
                ('usuario', models.ForeignKey(
                    on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SintomaModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SituacionHabitacionalModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SituacionLaboralModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TallerModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TallerPacienteModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='crm.pacientemodel')),
                ('taller', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='crm.tallermodel')),
            ],
        ),
        migrations.CreateModel(
            name='TerapiaRehabilitacionModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TratamientoModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('medicoTratante', models.CharField(max_length=300)),
                ('tratamiento', models.CharField(max_length=300)),
                ('droga', models.CharField(max_length=300)),
                ('marca', models.CharField(max_length=300)),
                ('paciente', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='crm.pacientemodel')),
                ('usuarioQueCargoTratamiento', models.ForeignKey(
                    on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtendidoModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=300)),
                ('fechaNacimiento', models.DateField()),
                ('telFijo', models.CharField(blank=True, max_length=300, null=True)),
                ('telMovil', models.CharField(max_length=300)),
                ('area', models.ForeignKey(
                    on_delete=django.db.models.deletion.RESTRICT, to='crm.areamodel')),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
        migrations.AddField(
            model_name='tallermodel',
            name='pacientes',
            field=models.ManyToManyField(
                through='crm.TallerPacienteModel', to='crm.PacienteModel'),
        ),
        migrations.AddField(
            model_name='pacientemodel',
            name='situacionHabitacional',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to='crm.situacionhabitacionalmodel'),
        ),
        migrations.AddField(
            model_name='pacientemodel',
            name='situacionLaboral',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to='crm.situacionlaboralmodel'),
        ),
        migrations.AddField(
            model_name='pacientemodel',
            name='talleres',
            field=models.ManyToManyField(
                through='crm.TallerPacienteModel', to='crm.TallerModel'),
        ),
        migrations.AddField(
            model_name='pacientemodel',
            name='usuarioQueRealizoAlta',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grupodeapoyopacientemodel',
            name='paciente',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='crm.pacientemodel'),
        ),
        migrations.AddField(
            model_name='grupodeapoyomodel',
            name='pacientes',
            field=models.ManyToManyField(
                through='crm.GrupoDeApoyoPacienteModel', to='crm.PacienteModel'),
        ),
        migrations.AddField(
            model_name='domiciliousuarioextendidomodel',
            name='provincia',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to='crm.provinciamodel'),
        ),
        migrations.AddField(
            model_name='domiciliousuarioextendidomodel',
            name='usuarioExtendido',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='crm.usuarioextendidomodel'),
        ),
        migrations.AddField(
            model_name='domiciliopacientemodel',
            name='paciente',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='crm.pacientemodel'),
        ),
        migrations.AddField(
            model_name='domiciliopacientemodel',
            name='provincia',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to='crm.provinciamodel'),
        ),
        migrations.AddField(
            model_name='domicilioalternativopacientemodel',
            name='paciente',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='crm.pacientemodel'),
        ),
        migrations.AddField(
            model_name='domicilioalternativopacientemodel',
            name='provincia',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to='crm.provinciamodel'),
        ),
        migrations.AddField(
            model_name='cuotapagamodel',
            name='paciente',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='crm.pacientemodel'),
        ),
        migrations.AddField(
            model_name='cuotapagamodel',
            name='usuarioQueCargoPago',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='composicionfamiliarmodel',
            name='paciente',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='crm.pacientemodel'),
        ),
    ]
