# Generated by Django 3.1.4 on 2020-12-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20201209_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='derivacion',
            old_name='areaAlQueSeDerivo',
            new_name='areaALaQueSeDerivo',
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='piso',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telFijo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
