# Generated by Django 3.1.4 on 2020-12-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20201209_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='derivacion',
            old_name='areaALaQueSeDerivo',
            new_name='areaAlQueSeDerivo',
        ),
    ]
