# Generated by Django 3.1.4 on 2020-12-14 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20201214_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tallermodel',
            name='pacientes',
        ),
    ]
