# Generated by Django 3.1.4 on 2020-12-14 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_tallermodel_pacientes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientemodel',
            old_name='areaALaQueSeDerivo_id',
            new_name='areaALaQueSeDerivo',
        ),
        migrations.RenameField(
            model_name='pacientemodel',
            old_name='usuarioQueRealizoAlta_id',
            new_name='usuarioQueRealizoAlta',
        ),
    ]
