# Generated by Django 3.1.4 on 2021-01-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_usuariomodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariomodel',
            name='user',
        ),
    ]
