# Generated by Django 3.1.4 on 2021-01-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_auto_20210106_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composicionfamiliarmodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
