# Generated by Django 3.1.4 on 2021-01-06 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0023_auto_20210106_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamientomodel',
            name='usuarioQueCargoTratamiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
